#ddev-generated
# If you remove the ddev-generated line above you
# are responsible for maintaining this file. DDEV will not then
# update it, for example if you add `additional_hostnames`, etc.

http:
  routers:
    cc-web-80-http:
      entrypoints:
        - http-80
      rule: HostRegexp(`^cc\.ddev\.site$`)

      service: "cc-web-80"
      ruleSyntax: v3
      tls: false
      # middlewares:
      #   - "cc-redirectHttps"
    cc-web-8025-http:
      entrypoints:
        - http-8025
      rule: HostRegexp(`^cc\.ddev\.site$`)

      service: "cc-web-8025"
      ruleSyntax: v3
      tls: false
      # middlewares:
      #   - "cc-redirectHttps"
    cc-xhgui-80-http:
      entrypoints:
        - http-8143
      rule: HostRegexp(`^cc\.ddev\.site$`)

      service: "cc-xhgui-80"
      ruleSyntax: v3
      tls: false
      # middlewares:
      #   - "cc-redirectHttps"



    cc-web-80-https:
      entrypoints:
        - http-443
      rule: HostRegexp(`^cc\.ddev\.site$`)

      service: "cc-web-80"
      ruleSyntax: v3

      tls: true

    cc-web-8025-https:
      entrypoints:
        - http-8026
      rule: HostRegexp(`^cc\.ddev\.site$`)

      service: "cc-web-8025"
      ruleSyntax: v3

      tls: true


    cc-xhgui-80-https:
      entrypoints:
        - http-8142
      rule: HostRegexp(`^cc\.ddev\.site$`)

      service: "cc-xhgui-80"
      ruleSyntax: v3

      tls: true



  middlewares:
    cc-redirectHttps:
      redirectScheme:
        scheme: https
        permanent: true

  services:
    cc-web-80:
      loadbalancer:
        servers:
          - url: http://ddev-cc-web:80

    cc-web-8025:
      loadbalancer:
        servers:
          - url: http://ddev-cc-web:8025



    cc-xhgui-80:
      loadbalancer:
        servers:
          - url: http://ddev-cc-xhgui:80




tls:
  certificates:
    - certFile: /mnt/ddev-global-cache/traefik/certs/cc.crt
      keyFile: /mnt/ddev-global-cache/traefik/certs/cc.key
